import type { CardData } from '../types'

export const intelCards: Record<string, CardData[]> = {
  'ch-intel-01': [
    { name: 'Intel 4004', year: '1971', codename: '4004', transistors: '2,300', clock: '740 kHz', cores: '1', threads: '1', cache: 'N/A', tdp: '0.5W', highlight: 'World\'s first microprocessor — a 4-bit CPU that started it all', variant: 'cpu', features: ['4-bit processor', '2,300 transistors on 10µm', '740 kHz clock', '4-bit data bus', '640 bytes addressable'], transistorScale: 0.01 },
    { name: 'Intel 8086', year: '1978', codename: '8086', transistors: '29K', clock: '5 MHz', cores: '1', threads: '1', cache: 'N/A', tdp: '1.5W', highlight: 'The x86 architecture was born — still dominant 45+ years later', variant: 'cpu', features: ['16-bit processor', 'x86 instruction set', '1MB address space', '6-byte instruction prefetch queue', 'Intel 8087 FPU support'], transistorScale: 0.01 },
    { name: 'Intel 386 DX', year: '1985', codename: 'P3', transistors: '275K', clock: '16 MHz', cores: '1', threads: '1', cache: 'N/A', tdp: '2W', highlight: '32-bit x86 — protected mode, virtual memory, Windows ready', variant: 'cpu', features: ['32-bit architecture', 'Protected mode', 'Virtual memory paging', 'Intel 80387 FPU support', 'Up to 4GB addressable'], transistorScale: 0.01 },
    { name: 'Intel 486 DX', year: '1989', codename: 'P4', transistors: '1.2M', clock: '25 MHz', cores: '1', threads: '1', cache: '8KB L1', tdp: '5W', highlight: 'Integrated FPU and cache — first truly modern CPU design', variant: 'cpu', features: ['Integrated FPU', '8KB L1 cache', '5-stage pipeline', '33 MHz bus', '1.2 million transistors'], transistorScale: 0.02 },
    { name: 'Pentium', year: '1993', codename: 'P5', transistors: '3.1M', clock: '60 MHz', cores: '1', threads: '1', cache: '16KB L1', tdp: '15W', highlight: 'Superscalar x86 — two pipelines made Pentium legendary', variant: 'cpu', features: ['Superscalar (dual pipeline)', '64-bit data bus', '16KB L1 cache', 'Branch prediction', 'FPU on die'], transistorScale: 0.02 },
  ],
  'ch-intel-02': [
    { name: 'Pentium Pro', year: '1995', codename: 'P6', transistors: '5.5M', clock: '150 MHz', cores: '1', threads: '1', cache: '256KB L2', tdp: '29W', highlight: 'Out-of-order execution — P6 architecture defined Intel for a decade', variant: 'cpu', features: ['Out-of-order execution', 'Superpipelined', '256KB-1MB L2 cache on-package', '36-bit addressing', 'Speculation'], transistorScale: 0.02 },
    { name: 'Pentium III 1GHz', year: '2000', codename: 'Coppermine', transistors: '28.1M', clock: '1000 MHz', cores: '1', threads: '1', cache: '32KB L1, 256KB L2', tdp: '33W', highlight: 'First 1GHz Intel CPU — SSE instructions for multimedia', variant: 'cpu', features: ['1GHz clock', 'SSE instructions', '256KB on-die L2 cache', '0.18µm process', '100MHz FSB'], transistorScale: 0.03 },
    { name: 'Pentium 4 HT', year: '2002', codename: 'Northwood', transistors: '55M', clock: '3060 MHz', cores: '1', threads: '2', cache: '8KB L1, 512KB L2', tdp: '83W', highlight: 'NetBurst peaked here — hyper-threading, very high clocks', variant: 'cpu', features: ['NetBurst architecture', 'Hyper-Threading (2 threads)', '3.06GHz clock', '400MHz FSB', 'SSE2'], transistorScale: 0.05 },
    { name: 'Core 2 Duo E6600', year: '2006', codename: 'Conroe', transistors: '291M', clock: '2400 MHz', cores: '2', threads: '2', cache: '64KB L1, 4MB L2', tdp: '65W', highlight: 'Core architecture — back from NetBurst, crushed AMD in perf/watt', variant: 'cpu', features: ['Core microarchitecture', '4MB shared L2 cache', 'Intel Wide Dynamic Execution', '65nm process', '1066MHz FSB'], transistorScale: 0.08 },
  ],
  'ch-intel-03': [
    { name: 'Core i7-920', year: '2008', codename: 'Bloomfield', transistors: '731M', clock: '2660 MHz', cores: '4', threads: '8', cache: '256KB L2, 8MB L3', tdp: '130W', highlight: 'Nehalem — integrated memory controller, QPI, turbo boost, the i7 era', variant: 'cpu', features: ['Nehalem architecture', 'Integrated DDR3 memory controller', 'QuickPath Interconnect', 'Turbo Boost', '4 cores / 8 threads', 'LGA1366'], transistorScale: 0.12 },
    { name: 'Core i7-2600K', year: '2011', codename: 'Sandy Bridge', transistors: '995M', clock: '3400 MHz', cores: '4', threads: '8', cache: '256KB L2, 8MB L3', tdp: '95W', highlight: 'Sandy Bridge — massive IPC leap, legendary overclocker', variant: 'cpu', features: ['Sandy Bridge architecture', 'Ring bus interconnect', 'Integrated HD Graphics 3000', 'AVX instructions', '32nm process', 'HDMI/DP from CPU'], transistorScale: 0.15 },
    { name: 'Core i7-4770K', year: '2013', codename: 'Haswell', transistors: '1.4B', clock: '3500 MHz', cores: '4', threads: '8', cache: '256KB L2, 8MB L3', tdp: '84W', highlight: 'Haswell — AVX2, FMA3, efficiency, the last great LGA1150', variant: 'cpu', features: ['Haswell architecture', 'AVX2 / FMA3', 'L4 eDRAM (Iris Pro variants)', 'TSX (Transactional Memory)', '22nm FinFET', 'LGA1150'], transistorScale: 0.20 },
  ],
  'ch-intel-04': [
    { name: 'Intel i740', year: '1998', codename: 'Auburn', transistors: '3.5M', clock: '66 MHz', cudaCores: 'N/A', memory: '8MB SDRAM', highlight: 'Intel\'s first discrete GPU — AGP 2x but poor DirectX performance', features: ['AGP 2x interface', '2D/3D acceleration', '8MB memory', 'Intel740 architecture', 'DirectX 6 support'], transistorScale: 0.01 },
    { name: 'HD Graphics 4000', year: '2012', codename: 'Ivy Bridge GT2', transistors: '1.4B', clock: '650 MHz', cudaCores: 'N/A', memory: 'System RAM (up to 2GB)', highlight: 'Integrated GPU in Ivy Bridge — HD 4000 for mainstream laptops', features: ['16 execution units', 'DirectX 11.1', 'OpenGL 4.0', 'Quick Sync Video', '3 display support'], transistorScale: 0.05 },
    { name: 'Iris Pro 5200', year: '2014', codename: 'Haswell GT3e', transistors: '1.9B', clock: '800 MHz', cudaCores: 'N/A', memory: '128MB eDRAM + System', highlight: 'Iris Pro with eDRAM — Intel\'s best integrated graphics before Xe', features: ['40 execution units', '128MB L4 eDRAM cache', 'DirectX 11.2', 'OpenCL support', 'Crystalwell package'], transistorScale: 0.06 },
    { name: 'Iris Xe (96 EU)', year: '2020', codename: 'Tiger Lake GT2', transistors: '10B', clock: '1100 MHz', cudaCores: 'N/A', memory: 'System RAM (DDR4/LPDDR4x)', highlight: 'Xe architecture — Intel\'s serious integrated GPU, 96 EUs', features: ['Xe-LP architecture', '96 execution units', 'Intel Deep Link', 'AV1 decode', 'DirectX 12 Ultimate', 'Up to 4 displays'], transistorScale: 0.10 },
  ],
  'ch-intel-05': [
    { name: 'Core i9-12900K', year: '2021', codename: 'Alder Lake', transistors: '10.6B', clock: '3200 MHz', cores: '16', threads: '24', cache: '14MB L2, 30MB L3', tdp: '125W', highlight: 'Hybrid x86 — P-cores + E-cores, Intel\'s boldest CPU design in a decade', variant: 'cpu', features: ['Performance-hybrid architecture', '8 P-cores + 8 E-cores (16C/24T)', 'Intel 7 (10nm Enhanced)', 'DDR5 / PCIe 5.0', 'Thread Director', 'LGA1700'], transistorScale: 0.50 },
    { name: 'Core i9-14900K', year: '2023', codename: 'Raptor Lake', transistors: '11.8B', clock: '3200 MHz', cores: '24', threads: '32', cache: '32MB L2, 36MB L3', tdp: '125W', highlight: 'Raptor Lake — 24 cores, 6GHz boost, the ultimate hybrid refinement', variant: 'cpu', features: ['Raptor Cove P-cores + Gracemont E-cores', '8 P-cores + 16 E-cores (24C/32T)', '6.0GHz Turbo Boost', 'Intel 7 process', 'DDR5 / DDR5 support'], transistorScale: 0.60 },
  ],
  'ch-intel-06': [
    { name: 'Arc A770', year: '2022', codename: 'Alchemist', transistors: '21.7B', clock: '2100 MHz', cudaCores: 'N/A', memory: '16GB GDDR6', highlight: 'Intel\'s modern discrete GPU — Xe HPG with ray tracing', features: ['Xe HPG architecture', '32 Xe cores (4096 FP32 ALUs)', 'Ray tracing units', 'XeSS upscaling', '16GB GDDR6 256-bit', 'AV1 encode/decode'], transistorScale: 0.45 },
    { name: 'Arc B580', year: '2024', codename: 'Battlemage', transistors: '19.6B', clock: '2670 MHz', cudaCores: 'N/A', memory: '12GB GDDR6', highlight: 'Battlemage — Intel\'s second-gen GPU, great value and DX12 performance', features: ['Xe2 HPG architecture', '20 Xe2 cores', 'Ray tracing improvements', 'XeSS 2 with Frame Generation', '12GB GDDR6 192-bit', 'PCIe 4.0'], transistorScale: 0.65 },
    { name: 'Core Ultra 9 285K', year: '2024', codename: 'Arrow Lake', transistors: '17.8B', clock: '3500 MHz', cores: '24', threads: '24', cache: '40MB L2, 36MB L3', tdp: '125W', highlight: 'Arrow Lake — no SMT, tiled design, NPU for AI workloads', variant: 'cpu', features: ['Arrow Lake architecture', '8 P-cores + 16 E-cores (24C/24T)', 'Tiled die design (CPU/GPU/NPU/SOC)', 'Intel 20A / TSMC N3B hybrid', 'Integrated NPU 3 (13 TOPS)', 'LGA1851'], transistorScale: 0.75 },
  ],
  'ch-intel-07': [
    { name: 'Xeon Platinum 8380', year: '2021', codename: 'Ice Lake-SP', transistors: '11.8B', clock: '2300 MHz', cores: '40', threads: '80', cache: '60MB L3', tdp: '270W', highlight: 'Ice Lake Xeon — PCIe 4.0, DDR4, 40 cores for enterprise', variant: 'cpu', features: ['Ice Lake-SP architecture', '40 cores / 80 threads', '10nm process', 'DDR4-3200 (8-channel)', 'PCIe 4.0 (64 lanes)', 'SGX, AVX-512'], transistorScale: 0.55 },
    { name: 'Xeon 6980P', year: '2024', codename: 'Granite Rapids', transistors: '15.6B', clock: '2200 MHz', cores: '128', threads: '256', cache: '504MB L3', tdp: '500W', highlight: '128-core Granite Rapids — Intel\'s data center answer to EPYC', variant: 'cpu', features: ['Granite Rapids architecture', '128 cores / 256 threads', 'Intel 3 process', 'DDR5-6400 (12-channel)', 'PCIe 5.0 (96 lanes)', 'AMX (Advanced Matrix Extensions)'], transistorScale: 0.80 },
  ],
}
